services:
  broker-service:
    build:
      context: .
      dockerfile: ./broker-service/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1