services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth
    ports:
      - "3000:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=logs
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/logs --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - mongo-data:/data/db

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  broker-service:
    depends_on:
      - auth-service
      - logger-service
      - mail-service
      - listener-service
    build:
      context: .
      dockerfile: ./broker-service/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./listener-service/Dockerfile
    restart: always
    ports:
      - "5050:5050"
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    restart: always
    ports:
      - "9090:9090"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DB_SOURCE=postgresql://root:password@go-microservices-postgres-1:5432/auth?sslmode=disable

  logger-service:
    depends_on:
      mongo:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./logger-service/Dockerfile
    restart: always
    ports:
      - "7070:7070"
    deploy:
      mode: replicated
      replicas: 1

  mail-service:
    depends_on:
      - mailhog
    build:
      context: .
      dockerfile: ./mail-service/Dockerfile
    restart: always
    ports:
      - "6060:6060"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - MAIL_DOMAIN=localhost
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_ENCRYPTION=none
      - FROM_NAME=John Doe
      - FROM_ADDRESS=john.doe@example.com

volumes:
  postgres-data:
  mongo-data: